### PR TITLE
Dockerize BellyDynamic 

### PR DESCRIPTION
**Pull request by kmehant**
Successfully built the docker and verified. @agentmilindu

### CODE REVIEW

**Review by agentmilindu — CHANGES_REQUESTED** [review]

**Comment by kmehant** [comment]
@agentmilindu Done, i removed the setup.sh file

I din't checkout the other pull request on creating setup.sh, i missed that sorry about it. 

The Dockerfile is valid and running properly, i checked on my local

**Comment by SamTube405** [comment]
Dockerfile needs to exclude setup.sh, Ideally this needs to install relevant libs (For snap; use install-snap-python.sh, and please include commands to install 'pandas')

**Review by sameeravithana — CHANGES_REQUESTED** [review]
Dockerfile needs to exclude setup.sh, Ideally this needs to install relevant libs (For snap; use install-snap-python.sh, and please include commands to install 'pandas')

**Comment by kmehant** [comment]
@SamTube405 I think we can place a requirements.txt and do ```pip install -r requirements.txt```

So, within requirements.txt, i will place the dependancies like pandas and other libs which we might need.

And for the ```setup.sh``` I'm not sure, because the dockerfile looks clumsy if place all the commands under RUN

@agentmilindu

**Comment by agentmilindu** [comment]
Let's do the changes in a new PR

**Comment by agentmilindu** [comment]
Links to #12

**Pull request merged**
