### PR TITLE
Add Shell Script to setup BellyDynamic

### PR DESCRIPTION
**Pull request by padamchopra**
Added a shell script to setup BellyDynamic, with the latest version of snap
[GCI 2017]

### CODE REVIEW

**Comment by iammosespaulr** [comment]
Hey buddy your script won't work
the wget link is outdated 
snap-4.0.0-4.0-centos6.5-x64-py2.6.tar.gz                     <---- the name of the latest package

**Comment by padamchopra** [comment]
@SamTube405 Here's the PR, please review and merge if you find this ok :)

**Review by agentmilindu — APPROVED** [review]
LGTM

**Comment by SamTube405** [comment]
This script only includes the installation of snap lib. in fact, you can find the same in ./install-snap-python.sh . I suggest you to include a complete script to setup the project, might be this task is related with dockerizing.

**Comment by padamchopra** [comment]
@SamTube405 I got a file not found error while running that script, so that's why I created this one. 
Also, this is not the dockerizing task. The task was just to run BellyDynamic and I created the shell-script on my own, but turns out its not of any use now :worried:

**Comment by padamchopra** [comment]
Can any of the maintainers of BellyDynamic add the instruction to install using the shell script in the [wiki](https://github.com/scorelab/BellyDynamic/wiki/Getting-Started) as well

**Comment by agentmilindu** [comment]
Let's use this `setup.sh` in Docker file with all the needed pckages for the Docker images to run.

**Comment by agentmilindu** [comment]
Links to  #12

**Pull request merged**
